name: Executar aportes recorrentes

on:
  schedule:
    - cron: "0 9 * * *"

  workflow_dispatch:

jobs:
  executar:
    runs-on: ubuntu-latest

    steps:
      - name: Executar aportes recorrentes
        run: |
          curl -X POST \
            -H "X-Cron-Key: ${{ secrets.CRON_SECRET }}" \
            "https://accuracyappapi.onrender.com/user/executarAportesRecorrentes.php"